### ISSUE TITLE
New wiki page: how it works

### ISSUE THREAD

**Issue by larsga** [larsga/Duke#113]
_From [lar...@gmail.com](https://code.google.com/u/106380900043315593284/) on March 06, 2013 09:39:05_

Write up a short, sweet explanation of how Duke works.

_Original issue: http://code.google.com/p/duke/issues/detail?id=112_

**Comment by edolix** [comment]
Hi @larsga . I was reading the wiki page at https://github.com/larsga/Duke/wiki/HowItWorks and i don't understand the operations to go from a similarity to a probability. 

On the `address` property we have `low: 0.25` and `high: 0.65` but which is the formula to get `prob = 0.6127` from `sim = 0.867` ?

```java
---ADDRESS1
'main street 101' ~ 'mian street 101': 0.867 (prob 0.6127)
Result: 0.5 -> 0.6127

---NAME
'j. random hacker' ~ 'john random hacker': 0.8 (prob 0.78542)
Result: 0.6127 -> 0.8527

---ZIP
'21231' ~ '21231': 1.0 (prob 0.6)
Result: 0.8527 -> 0.8967

Overall: 0.8967
```

Thanks!

**Comment by fabriziofortino** [comment]
@edolix you can find the formula (with explanation) here https://github.com/larsga/Duke/blob/master/duke-core/src/main/java/no/priv/garshol/duke/PropertyImpl.java#L134-L154

**Comment by edolix** [comment]
Thanks @fabriziofortino! 

I read this formula and if i replace values from the doc page we have:

`name` property with `low: 0.35` and `high: 0.88`. Similarity to `0.8` and probability to `0.78542`.

But applying the formula:  `((0.88 - 0.5) * (0.8 * 0.8)) + 0.5 = 0.7432`

Could be an error in page, or maybe there was some code's differences when the examples was written. Just to be sure to read my matches in the right way!

**Comment by fabriziofortino** [comment]
@edolix 

`high` is 0.65

the applied formula is: 
```
((0.65 - 0.5) * (0.867 * 0.867)) + 0.5 = 0.61275335
```

**Comment by edolix** [comment]
For the address field yes, it's right!
But for the `name` property there is something that i don't understand

**Comment by fabriziofortino** [comment]
I think for the `name` property there is a mistake in the documentation. Probability should be `0.7432`
