### ISSUE TITLE
Modular project structure

### ISSUE THREAD

**Issue by fabriziofortino** [larsga/Duke#150]
This is a proposal to change the overall project structure creating separate modules (the change has been initially discussed in #147 ). The project structure will be something like this:

- **/** (project root, contains the parent pom file)
- **/duke-core** (core module, contains the core logic)
- **/duke-lucene** (depends from core, contains the lucene db implementation)
- **/duke-mapdb** (depends from core, contains the mapdb db implementation)
- **/duke-es** (depends from core, contains the elasticsearch db implementation). This is almost ready, I am working on it.
- **/duke-server** (depends from core, contains the server implementation)

New sub-modules (an example could be a python cleaner/comparator interpreter discussed #147)  could be easily added in a separate module.

This change implies that the default database will not be lucene anymore (can we set the InMemoryDatabase as the default one?). I would not keep the lucene dependency in the core because other modules (eg: duke-es) or projects using duke would indirectly use different version of lucene underneath.

WDYT? Can we create a separate branch to work on this?

**Comment by drazzib** [comment]
Hi everyone!

I've started working providing a modular structure for Duke.
You can find my Work In Progress in [dictanova/duke](https://github.com/larsga/Duke/compare/master...Dictanova:modular_project) repository.

Regards,
