### ISSUE TITLE
Extend RegexpCleaner to discard all matches instead only the first

### ISSUE THREAD

**Issue by qtips** [larsga/Duke#189]
When running RegexpCleaner in discard mode, it only discards first match. If you for example wish to remove all occurrences of a certain character , you will need to re-run the RegexpCleaner several times. 

string: "I123Dont454Like450Di3gits"
regex: "(\d+)"
result now: "IDont454Like450Di3gits"
should be possible to get: "IDontLikeDigits"

It is suggested that RegexpCleaner is extended with a new flag so that all occurrences on a match can be discarded.

**Comment by larsga** [comment]
qtips implemented this himself, and the pull request has been merged.
