### ISSUE TITLE
Problem with NumericComparator

### ISSUE THREAD

**Issue by iDmple** [larsga/Duke#216]
Hi Lars,

I'm not sure whether the NumericComparator is made to be used in this case, but it makes the final probability negative:

---FloorNumber
'-2' ~ '-1': 2.0 (prob 1.1)
Result: 0.037589897356784224 -> -0.7532754191891153

Here is my property:
        <property>
            <name>FloorNumber</name>
            <comparator>no.priv.garshol.duke.comparators.NumericComparator</comparator>
            <low>0.3</low>
            <high>0.65</high>
        </property>

What do you advise in this case?

Best regards

**Comment by larsga** [comment]
This looks very strange, but it's probably a bug. Let me investigate a little and see if I can fix it.

I'm not sure if this is the right comparator for your purposes, though. How different is floor "-2" from floor "2"? Should "1" ~ "2" and "8" ~ "16" compare as equally similar?

I'll fix the bug anyway.

**Comment by iDmple** [comment]
Hi,

indeed it isn't the right comparator for me. I need something like |v1-v2|, but for now I just used the exact comparator and it works as well. I might implement some more comparators in the future if needed. I'll share them with you.

**Comment by larsga** [comment]
If you do implement more comparators then pull requests are very welcome. :)

**Comment by larsga** [comment]
Fixed by commit 033661fa575ec4536c47fe96643813265a942979

**Comment by iDmple** [comment]
Many thanks!
