### ISSUE TITLE
Similarity of columns

### ISSUE THREAD

**Issue by Edwin2664** [larsga/Duke#218]
Hi, 
May I know if there is anyway to have similarity of each column while running Duke in Recordlinkage mode ? right now I have overall similarity but I would like to have it for each column too.
Thanks
Edwin

**Comment by larsga** [comment]
You mean, can you get the comparison value for one specific column for two specific records? Yes, that's possible, either using the DebugCompare command-line program, or using the API. How is it you want this?

**Comment by larsga** [comment]
Closing this as probably irrelevant now.
