### ISSUE TITLE
Exclude record if field is null

### ISSUE THREAD

**Issue by Off76** [larsga/Duke#219]
Hi,

Is that possible to configure Duke to exclude a record if a field used for comparison is null ? I searched it in the wiki but I didn't find it.

I don't know if this is better to have a parameter in the XML configuration file or if I need to exclude them directly on the datafile.

Thanks !

**Comment by larsga** [comment]
What do you mean by exclude? Not include it in deduplication/linkage at all? Or reject it as not matching?

What data source are you using?

**Comment by Off76** [comment]
I mean not include it in dedup process at all. 
I'm using the CSV data source !

**Comment by larsga** [comment]
There is no feature for that at the moment. It seemed kind of a waste to build a whole filtering language (which this quickly develops into) for something that you can do in 3 lines of Python before running the data through Duke.

It *is* of course possible to write your own data source that wraps the CSV data source, but the script is about 40 times easier.

**Comment by Off76** [comment]
Yep you're right, thanks !
