### ISSUE TITLE
DebugCompare "Couldn't find record for my ID"

### ISSUE THREAD

**Issue by Eugeneifes** [larsga/Duke#220]
I am trying to tune Duke 1.2 to choose the best functions (Comparators and Cleaners) and parameters (thresholds) for processing my data (record linkage task)
For these purposes i use **DebugCompare** class as it is described in the [TuningGuide](https://github.com/larsga/Duke/wiki/TuningGuide):

`java no.priv.garshol.duke.DebugCompare <xmlfile> <id1> <id2>`

The way i do it:
`java -cp ..\..\..\duke-1.2.jar;..\..\..\duke-1.2-javadoc.jar;..\..\..\duke-1.2-sources.jar;..\..\..\lucene-analyzers-common-4.0.0.jar;..\..\..\lucene-core-4.0.0.jar;..\..\..\lucene-queries-4.0.0.jar;..\..\..\lucene-spatial-4.0.0.jar;..\..\..\mapdb-0.9.9.jar;..\..\..\spatial4j-0.3.jar no.priv.garshol.duke.DebugCompare powerplant.xml 1 2`

As it is required i have Lucene index on disk (database configuration in my XML file):
` <database class="no.priv.garshol.duke.databases.LuceneDatabase">
         <param name="path" value="luke"/>
 </database>`

By the way, index was created successfully, i can access its objects using Luke

During debug i tried different methods of using OnDiskDatabase
I also tried to access elements in an existing Lucene database through `<path>` tag in my config XML:

`<path>luke</path>`

But the command line constantly returns me:

```
Couldn't find record for '1'
Consider using --reindex
```

I also tried to add --reindex to my command, but result was still the same (another index was created next to the first one in the same directory)

Finally I tried to use property ID as object ID in my commad (the result was also the same):
I know this is surely incorrect, because Lucene use its own IDs, and property ID acts in each object as usual field

What am i do wrong?
Am I use wrong way to connect to the existing index?
What field the interpreter wants me to use as an ID?

**Comment by Eugeneifes** [comment]
Sorry for creating this issue, i figured it out!
For anyone, who would have to deal with such problem:

1) Don't create index on Disk before Debug (do Debug and create index on disk at the same time)
2) Use property ID as ID in the command

**Comment by larsga** [comment]
Glad to see you figured it out! And thanks for documenting the solution.
