### ISSUE TITLE
Packaging duke-core separately

### ISSUE THREAD

**Issue by pcx** [larsga/Duke#223]
Hi,

Are there any plans to package and publish duke-core separately?

We are exploring Duke currently for a project at my company. We have a custom wrapper for ElasticSearch and are planning to use duke-core for dedup. But the Lucene dependency in Duke and ElasticSearch Java API are clashing. So we are planning to manually package duke-core instead of using the whole project. It would be great if the package was available from maven and we could just pull it from there.

**Comment by fabriziofortino** [comment]
1.3-SNAPSHOT provides this separation (not sure when @larsga plans to release it). Moreover there is an ElasticSearch module (https://github.com/larsga/Duke/tree/master/duke-es) to use replace Lucene with ES (need some documentation though).

**Comment by larsga** [comment]
I guess a 1.3 release is way overdue. I will try to push it out soon.

**Comment by pcx** [comment]
Hi @fabriziofortino, @larsga,

Thanks for the prompt reply. Regarding the ElasticSearch module, we saw that but went with a custom wrapper to fit our use-case better.

Looking forward to the 1.3 release, hope it won't take long.(We'll package it manually until then.) I am closing this issue.

Thanks
