### ISSUE TITLE
Add link to wikipedia for each comparator in Duke wiki

### ISSUE THREAD

**Issue by magdmartin** [larsga/Duke#231]
The https://github.com/larsga/Duke/wiki/Comparator  page briefly introduce the different comparators available in Duke. However, the level of details is not enough for someone new to those comparators. I think a link to the relevant English Wikipedia page should do the work.

I am OK to do it but I wanted to raise the issue here first (since Github wiki edits can easily go unnoticed)

**Comment by larsga** [comment]
Good idea! If you want, please feel free to go right ahead and do it.

**Comment by magdmartin** [comment]
wiki page updated.

**Comment by larsga** [comment]
Looks great! Thank you! :-)
