### ISSUE TITLE
Jaro-Winkler Comparator bugs

### ISSUE THREAD

**Issue by dipplestix** [larsga/Duke#247]
The Jaro-WInkler comparator as is has two bugs in it. 

1) The comparison is order dependent comparing (a, b) returns different results than (b, a)
2) There are issues with duplicated count when searching through s2.

I have a fix written, but need permission to create a branch

**Comment by michalkurka** [comment]
@dipplestix you should probably fork this project and create a PR to this one from your fork, I can help you with that

**Comment by larsga** [comment]
Yes, please fork and make a PR and we'll look at your fix. I haven't looked into it, but other people have identified the same two bugs in the Jaro-Winkler code, so I'm sure you're right.

**Comment by dipplestix** [comment]
Fixed in https://github.com/larsga/Duke/pull/248
