### ISSUE TITLE
No identity for records

### ISSUE THREAD

**Issue by xinelim** [larsga/Duke#263]
Hi,
I am encountering an issue, Exception in thread "main" no.priv.garshol.duke.DukeException: No identity for record [CompactRecord {}]. The commands were working well for my previous dataset. May I know what is the cause for this issue? Thank you!

**Comment by larsga** [comment]
Probably you have a record with no value for the identity field. From the error message it looks like that record has no values at all. Duke can't work with that, because there's no way to identify the record.

**Comment by xinelim** [comment]
Problem solved. I downloaded my dataset again and it works now.
