### ISSUE TITLE
Allow multiple matches for record linkage

### ISSUE THREAD

**Issue by larsga** [larsga/Duke#56]
_From [FMitzl...@googlemail.com](https://code.google.com/u/100150341542670259884/) on November 07, 2011 09:22:15_

Currently only the best match per record is propagated to the given MatchListener (see Processor.matchRL). In our use case we'd like to collect the top-k matches per item, leaving the ultimate choice to the user.

The easy way for implementing this behaviour would be to add a parameter to the link(...) method. But maybe there is an efficient way of implementing a 'meta matcher' which just implements the 'best match' semantics and passes the 'final' match to a registered MatchListener ?

_Original issue: http://code.google.com/p/duke/issues/detail?id=55_

**Comment by Afbcary** [comment]
So is there a way to get the top-k matches of one entry from a datasource to several entries from another datasource in RecordLinkageMode? Is there any documentation or any examples of this?
